/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Freemodels (https://sketchfab.com/vivaanarora9)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-c9ba17582be94c6f8b610eede5f060cf
Title: Earth
*/

import React, { useRef } from "react";
// import { useGLTF } from "@react-three/drei";
import { useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useMotionValue, useSpring } from "motion/react";
import { useFrame } from "@react-three/fiber";

export function Astronaut(props) {
  const group = useRef();

  const { nodes, materials, animations } = useGLTF("/models/world.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      rotation={[-Math.PI / 2, -0.2, 2.2]}
      scale={props.scale || 6.2}
      position={props.position || [1.3, -1, 0]}
    >
      <group rotation={[-Math.PI / 2, 0.004, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials.Earth_Diffuse_6K}
            rotation={[-0.528, 1.129, 0.119]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_6.geometry}
            material={materials["Material.001"]}
            rotation={[-0.528, 1.129, 0.119]}
            scale={1.002}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/world.glb");
